### ISSUE TITLE
Web client support

### ISSUE THREAD

**Issue by quendera** [FrogSquare/GodotFireBase#16]
Hi,

I'm looking at using firebase on a cross-platform app. Are you considering expanding from android exclusive?

**Comment by RameshRavone** [comment]
Sorry, not at the moment, but for 3.0 yes through cpp.

**Comment by quendera** [comment]
Thank you for the prompt reply.
I'm looking for a service (can't setup local server in my work network) to where I can send whatever file with data from my game (pref. .json). 

GodotFireBase solves it for android... ideas on which db client I could use cross-platform with godot?

sqlite, mongodb and firebase seem to all be waiting for 3.0.

**Comment by RameshRavone** [comment]
> send whatever file with data from my game
Are you talking about the level data.

For storage I'd go with sqlite for now, and can migrate to FireBase. I'll try to fasten firebase CPP as soon as I complete my AIParser for Utility AI,

**Comment by quendera** [comment]
>>send whatever file with data from my game

>Are you talking about the level data.

I basically have a dict with some variables that I want to save to a db. 

>For storage I'd go with sqlite for now, and can migrate to FireBase. I'll try to fasten firebase CPP as soon as I complete my AIParser for Utility AI,

That's what I thought, thank you ;)
