### ISSUE TITLE
Failure to call FireBase class on android export.

### ISSUE THREAD

**Issue by quendera** [FrogSquare/GodotFireBase#17]
Hi, 
Thanks again for the great feature.

I'm struggling to get GodotFirebase to work on my android devices and my feeling is that I'm missing something about the way to compile godot with the module.

What I observe:
-All the java files are not being redirected to their respective directories like they should on compilation to platform=x11.
-I get a missing class error on running an exported example on android: full error https://pastebin.com/MLCVJEZn

My setup is:
Ubuntu 14
Godot 2.1-stable
java (and javac) 1.8.0_131
adb 1.0.32

please feel free to ask any questions. I'm also open to contribute if it's something minor. Once I figure this out I'll also help with some more detailed instructions for the readme so newcomers like me have an easier time.

**Comment by RameshRavone** [comment]
The title doesn't explain much, what do you mean by Failure to call FireBase class.

**Comment by quendera** [comment]
> The title doesn't explain much, what do you mean by Failure to call FireBase class.

my bad, hit return to do a paragraph and it submitted the issue.

**Comment by RameshRavone** [comment]
I don't get it what do you mean `platform=x11` to compile/export for android you should use `platform=android` http://docs.godotengine.org/en/stable/development/compiling/compiling_for_android.html

**Comment by quendera** [comment]
On compiling for platform=android I get an error on google services:

/godot$ scons platform=android
scons: Reading SConscript files ...
sh: 1: i586-mingw32msvc-gcc: not found
sh: 1: i686-w64-mingw32-gcc: not found
Godot Android!!!!! (armv7) (with neon)
AttributeError: 'SConsEnvironment' object has no attribute 'android_add_gradle_classpath':
  File "/home/<mypath>/godot/SConstruct", line 316:
    config.configure(env)
  File "./modules/GodotFireBase/config.py", line 10:
    env.android_add_gradle_classpath("com.google.gms:google-services:3.0.0")

**Comment by RameshRavone** [comment]
Which version on Godot are you using.

**Comment by quendera** [comment]
a fresh clone of 2.1-stable.

**Comment by quendera** [comment]
I'm following the instructions you gave on [this discord channel] (https://discordapp.com/channels/266724176193126400/326990743442948107) and will get back with the result.

**Comment by RameshRavone** [comment]
Hope this issue has been resolved,
