### ISSUE TITLE
Analytics send_custom and send_events error

### ISSUE THREAD

**Issue by e9aru** [FrogSquare/GodotFireBase#23]
After calling `send_custom` I'm getting error:
` E godot   : **SCRIPT ERROR**: Invalid call. Nonexistent function 'send_custom' in base 'JNISingleton'`
(similar situation with `send_events`)

Other analytics methods, e.g `tutorial_begin` / `tutorial_complete` seems to work fine
I'm using 3.0.RC1

**Comment by RameshRavone** [comment]
Thanks and fixed it

**Comment by e9aru** [comment]
Thanks, that was crazy fast
Can confirm `send_custom` is now working like a charm, but `send_events` is not 😛
