### ISSUE TITLE
** SCRIPT ERROR **: Invalid call. Nonexistent function 'set_document' in base 'JNISingleton'.

### ISSUE THREAD

**Issue by diico** [FrogSquare/GodotFireBase#25]
Hi,

I followed the step by step to generate the templates and when running a simple example encounter the error:

** SCRIPT ERROR **: Invalid call. Nonexistent function 'set_document' in base 'JNISingleton'.

Note: I compiled on MAC

My code:

extends Node
var firebase

func _ready():
    firebase = Engine.get_singleton("FireBase")
    firebase.initWithFile("res://godot-firebase-config.json", get_instance_id())
	
	var dic = {
		"name": "Demo"
	}
	
	firebase.set_document("people", "person1", dic)

**Comment by RameshRavone** [comment]
Once adding he following to `engine.cfg` you have to launch the project fresh if you already had the  project opened
```
[android]
modules="org/godotengine/godot/FireBase,org/godotengine/godot/SQLBridge"
```

And check adb log for these
```
I/godot   (25335): ANDROID MODULES : org/godotengine/godot/FireBase,org/godotengine/godot/SQLBridge,org/godotengine/godot/GodotPanel,org/godotengine/godot/GooglePlay
I/godot   (25335): mod count: 4
I/godot   (25335): LOADING MODULE: org/godotengine/godot/FireBase
```

**Comment by diico** [comment]
I'm using Godot 3, the modules are loaded according to the log


02-10 11:04:15.392 26339 26367 I godot   : *****SETUP OK
02-10 11:04:15.392 26339 26367 I godot   : ANDROID MODULES : org/godotengine/godot/FireBase,org/godotengine/godot/SQLBridge
02-10 11:04:15.392 26339 26367 I godot   : mod count: 2
02-10 11:04:15.393 26339 26367 I godot   : LOADING MODULE: org/godotengine/godot/FireBase
02-10 11:04:15.393 26339 26367 I godot   : ****^*^*?^*^*class data 20004d
02-10 11:04:15.475 26339 26367 I godot   : ****^*^*?^*^*class instance 200051
02-10 11:04:15.475 26339 26367 I godot   : LOADING MODULE: org/godotengine/godot/SQLBridge
02-10 11:04:15.476 26339 26367 I godot   : ****^*^*?^*^*class data 200059
02-10 11:04:15.478 26339 26367 D godot   : SQLBridge:Initialized

02-10 11:04:16.049 26339 26367 E godot   : **SCRIPT ERROR**: Invalid call. Nonexistent function 'set_document' in base 'JNISingleton'.
02-10 11:04:16.049 26339 26367 E godot   :    At: res://Node.gdc:13:_ready() - Invalid call. Nonexistent function 'set_document' in base 'JNISingleton'.
02-10 11:04:16.052 26339 26339 D FireBase: Data From File: {"AdMob":false,"Authentication":true,"Invites":false,"RemoteConfig":false,"Notification":false,"Storage":false,"Firestore":true,"AuthConf":{"Google":false,"Twitter":false,"Facebook":false,"FacebookAppId":"","Anonymous":false,"EmailPassword":true},"Ads":{"AppId":"","BannerAd":false,"BannerGravity":"BOTTOM","BannerAdId":"","InterstitialAd":false,"InterstitialAdId":"","RewardedVideoAd":false,"RewardedVideoAdId":""}}
02-10 11:04:16.052 26339 26339 D FireBase: Initializing Firebase Analytics.
02-10 11:04:16.052 26339 26339 D FireBase: Firebase Analytics initialized..!
02-10 11:04:16.052 26339 26339 D FireBase: Initializing Firebase Authentication.
02-10 11:04:16.053 26339 26339 D FireBase: FireBase initialized.

The method below works:
firebase.alert ("Message goes here ..!");

I'll try Godot 2

**Comment by diico** [comment]
Friend,

Please disregard, I just realized that I should be using an adapted version (https://github.com/Dhciolfi/GodotFireBase).

Thank you very much for your attention.
