### ISSUE TITLE
Firebase loads but no banner at all...

### ISSUE THREAD

**Issue by marcusViniciusMP** [FrogSquare/GodotFireBase#29]
is this correct ?
func _ready():
	if Globals.has_singleton("FireBase"):
		dbg.set_text("FIREBASE ATIVO !")
		fireBase = Globals.get_singleton("FireBase")
		fireBase.show_banner_ad(true)

[debug.taptap.txt](https://github.com/FrogSquare/GodotFireBase/files/1843945/debug.taptap.txt)

**Comment by RameshRavone** [comment]
You skipped `initializing`

**Comment by RameshRavone** [comment]
```
func _ready():
    if OS.get_name() == "Android":
        firebase.initWithFile("res://godot-firebase-config.json", get_instance_ID());

func _receive_message(tag, from, key, data):
    if tag == "FireBase":
        print("From: ", from, " Key: ", key, " Data: ", data)
```

**Comment by marcusViniciusMP** [comment]
i did it but now its blinking....
func _ready():
	if OS.get_name() == "Android":
		firebase.initWithFile("res://google-services.json", get_instance_ID())
	
		fireBase = Globals.get_singleton("FireBase")
		fireBase.show_banner_ad(true)
[debug.taptap.txt](https://github.com/FrogSquare/GodotFireBase/files/1843950/debug.taptap.txt)

**Comment by marcusViniciusMP** [comment]
still no banner... :(

func _ready():
>	if OS.get_name() == "Android":
>>		fireBase = Globals.get_singleton("FireBase")
>>		fireBase.initWithFile("res://google-services.json", get_instance_ID())
	
>>		fireBase = Globals.get_singleton("FireBase")
>>		fireBase.show_banner_ad(true)

**Comment by RameshRavone** [comment]
Why are you using get_singleton again, save the instance as global variable, and you need to wait until banner loads, please check `README`

I spent lot of time on it,

**Comment by RameshRavone** [comment]
Once banner is loaded you will receive a callback in `_receive_message` function

**Comment by RameshRavone** [comment]
```
func _receive_message(tag, from, key, data):
    if tag == "FireBase" and from == "AdMob":
        if key == "AdMobReward":
            # when rewared video play complete
            print("json data with [RewardType & RewardAmount]: ", data);

        elif key == "AdMob_Video":
            # when rewarded video loaded
            # data will be `loaded` or `load_failed and `loaded` or `not_loaded` with `firebase.request_rewarded_video_status()`
            print("AdMob rewarded video status is ", data);

        elif key == "AdMob_Banner":
            # when banner loaded
            # data will be `loaded` or `load_failed`
            print("Banner Status: ", data);

        elif key == "AdMob_Interstitial" and data == "loaded":
            # when Interstitial loaded
            # data will be `loaded` or `load_failed`
            print("Interstitial Status: ", data);
``

**Comment by marcusViniciusMP** [comment]
i did this:


func _ready():
	if OS.get_name() == "Android":
		fireBase.initWithFile("res://google-services.json", get_instance_ID())
		dbg.set_text("firebase init")
		fireBase.show_banner_ad(true)
	else : dbg.set_text("nao funcionou")
	
#	get_tree().connect("screen_resized", self, "onResize")
	
func _receive_message(tag, from, key, data):
	if tag == "FireBase":
		if key == "AdMobReward":
			# when rewared video play complete
			dbg.set_text("json data with [RewardType & RewardAmount]: ", data);
		
		elif key == "AdMob_Video":
			# when rewarded video loaded
			# data will be `loaded` or `load_failed and `loaded` or `not_loaded` with `firebase.request_rewarded_video_status()`
			dbg.set_text("AdMob rewarded video status is ", data);
		
		elif key == "AdMob_Banner":
			# when banner loaded
			# data will be `loaded` or `load_failed`
			dbg.set_text("Banner Status: ", data);
		
		elif key == "AdMob_Interstitial" and data == "loaded":
			# when Interstitial loaded
			# data will be `loaded` or `load_failed`
			dbg.set_text("Interstitial Status: ", data);

but no banner appears

**Comment by marcusViniciusMP** [comment]
i did this:

func _ready():
	if OS.get_name() == "Android":
		fireBase.initWithFile("res://google-services.json", get_instance_ID())
		dbg.set_text("firebase init")
		fireBase.show_banner_ad(true)
	else : dbg.set_text("nao funcionou")
	
	
func _receive_message(tag, from, key, data):
	if tag == "FireBase":
		if key == "AdMobReward":
			dbg.set_text("json data with [RewardType & RewardAmount]: ", data);
		
		elif key == "AdMob_Video":
			dbg.set_text("AdMob rewarded video status is ", data);
		
		elif key == "AdMob_Banner":
			dbg.set_text("Banner Status: ", data);
		
		elif key == "AdMob_Interstitial" and data == "loaded":
			dbg.set_text("Interstitial Status: ", data);

but no banner i saw ...
