### ISSUE TITLE
still not working...

### ISSUE THREAD

**Issue by marcusViniciusMP** [FrogSquare/GodotFireBase#30]
i did this:
>func _ready():
>>if OS.get_name() == "Android":
>>>fireBase.initWithFile("res://godot.firebase.config.json", get_instance_ID())
>>>fireBase.show_banner_ad(true)
>>else : dbg.set_text("nao funcionou")
	
	
>func _receive_message(tag, from, key, data):
>>if tag == "FireBase":
>>>if key == "AdMobReward":
>>>>dbg.set_text("json data with [RewardType & RewardAmount]: ", data);
		
>>>elif key == "AdMob_Video":
>>>>dbg.set_text("AdMob rewarded video status is ", data);
		
>>>elif key == "AdMob_Banner":
>>>>dbg.set_text("Banner Status: ", data);
		
>>>elif key == "AdMob_Interstitial" and data == "loaded":
>>>>dbg.set_text("Interstitial Status: ", data);

i did not understand:

is the value appid from godot-firebase-config.json the id of project in firebase ?
where  i call the method to load the banner ?
why _receive_message is not receiving messages ? should i ivoke it ate ready too ?
shoud i put in godot-firebase-config.json admob = false to enable it ?

**Comment by marcusViniciusMP** [comment]
log:

D/FireBase(22009): Data From File: 
D/FireBase(22009): FireBase initialized.
D/FireBase(22009): AdMob:NotInitialized.

**Comment by RameshRavone** [comment]
First remove this `fireBase.show_banner_ad(true)` from `_ready`  and how is your json file, have you enabled AdMob and provided unit-ids

Refer README

**Comment by RameshRavone** [comment]
Move show_banner_to, _receive_message under `key == ""AdMob_Banner" `

**Comment by marcusViniciusMP** [comment]
"AdMob" : true,
	"Authentication" : true,
	"Invites" : true,
	"RemoteConfig" : true,
	"Notification" : true,
	"Storage" : true,
	"FireStore" : true,

	"AuthConf" : 
	{
		"Google" : true,
		"Twitter" : true,
		"Facebook" : true,
		"FacebookAppId" : "1234566789875"
	},

	"Ads" : 
	{
		"AppId": "taptapnotap",
		"BannerAd" : true,
		"BannerGravity" : "TOP",
		"BannerAdId" : "ca-app-pub-3839228269033318/7195598524",

		"InterstitialAd" : true,
		"InterstitialAdId" : "",

		"RewardedVideoAd" : true,
		"RewardedVideoAdId" : "",

**Comment by RameshRavone** [comment]
have you included *.json in resource section when exporting apk.

**Comment by marcusViniciusMP** [comment]
"taptapnotap" is the id of game in firebase, and i have included as i see in the screenshot in readme

**Comment by RameshRavone** [comment]
that is not, when you export for android from godot editor, you havd to
include *.json there, see README, last section

**Comment by RameshRavone** [comment]
https://github.com/FrogSquare/GodotFireBase/blob/master/README.md#note

**Comment by marcusViniciusMP** [comment]
yes i also did this:
https://camo.githubusercontent.com/3c6acbb5c71ebdd9bcf5d5f01aa945bdeb777b38/687474703a2f2f707265766965772e6962622e636f2f6654774338512f53637265656e73686f745f66726f6d5f323031375f30365f31375f31385f34345f32352e706e67
now debug message changed," D/FireBase(22009): AdMob:NotInitialized." not appears anymore but no banner indeed

**Comment by marcusViniciusMP** [comment]
what im seeing here is that this receive_message function receives no message at all... it just keep quiet...

**Comment by RameshRavone** [comment]
D/FireBase(22009): Data From File:

Shows your json is empty,

On 27-Mar-2018 6:45 am, "marcusViniciusMP" <notifications@github.com> wrote:

what im seeing here is that this receive_message function receives no
message at all... it just keep quiet...

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/FrogSquare/GodotFireBase/issues/30#issuecomment-376363136>,
or mute the thread

**Comment by marcusViniciusMP** [comment]
![screenshot from 2018-03-26 22-27-06](https://user-images.githubusercontent.com/32377313/37941515-ee94168e-3144-11e8-8f6f-b91e44e28080.png)

**Comment by RameshRavone** [comment]
do this and share the file,

```
adb logcat > logcat.txt
```

**Comment by marcusViniciusMP** [comment]
[logcat.txt](https://github.com/FrogSquare/GodotFireBase/files/1850096/logcat.txt)

ok !

**Comment by marcusViniciusMP** [comment]
[log2.txt](https://github.com/FrogSquare/GodotFireBase/files/1850102/log2.txt)

using adb -d logcat godot:V FireBase:V DEBUG:V AndroidRuntime:V ValidateServiceOp:V *:S

**Comment by RameshRavone** [comment]
There is something wrong with `File read`:

```
D/FireBase( 6570): Data From File: 
```
I pushed some debug prints for readFile, pull changes and recompile the export template

**Comment by RameshRavone** [comment]
And  to make sure the file is included in export, can you unzip the apk and see the `json` file inside `assets` folder

**Comment by marcusViniciusMP** [comment]
no json there !

**Comment by marcusViniciusMP** [comment]
what should i do now ?

**Comment by RameshRavone** [comment]
Sorry for the delay, it means the json is not exporting properly. make sure you enter `*.json` not `.json` in Resources section in Project Export Settings

**Comment by leofrozen** [comment]
Marcus, já tou ficando com pena do FrogSquare! XD
Já passei por um problema assim e no final era só uma bobagem que deixei passar.
Se quiser, me adiciona no Discord pra vê se consigo te ajudar: schroldinger#4896

**Comment by marcusViniciusMP** [comment]
yes im sure i do this, *.json , but again nothing happens.
​

**Comment by RameshRavone** [comment]
Hmm, since file not exporting lets use `Dictionary` variable in the gdscript

```
var firebase_config = {
"AdMob"      : true,
"Authentication" : true,
"Facebook"   : true,
"Google"     : true,
"Invites"    : true,
"Firestore"  : true,

"AuthConf"       : {
            "Google" : true,
            "Twitter" : true,
            "Facebook" : true,
            "FacebookAppID" : "1086088244850817"
           },

"Ads"        : {
            "AppId" : "ca-app-pub-1757432180145482~8303419758",
            "BannerAd" : true,
            "BannerGravity" : "BOTTOM",
            "BannerAdID" : "",

            "InterstitialAd" : true,
            "InterstitialAdID" : "",

            "RewardedVideoAd" : true,
            "RewardedVideoAdID" : ""
           }
}
```
and use `firebase.init(firebase_config.to_json(), get_instance_ID());`

**Comment by MatiasVME** [comment]
This way works for me :+1: 

`func _ready():
	var firebase = Engine.get_singleton("FireBase")
	
	if OS.get_name() == "Android":
		var file = File.new()
		file.open("res://godot-firebase-config.json", file.READ)
		var content = file.get_as_text()
		file.close()

		firebase.init(content, get_instance_id())

	if firebase != null:
		firebase.show_banner_ad(true)`
