### ISSUE TITLE
Failed to retrieve non-existent singleton 'FireBase'

### ISSUE THREAD

**Issue by TheTrope** [FrogSquare/GodotFireBase#37]
Hi,

First, thank you for writing this modules, looking forward to test it !
However, during setup I got the 'Failed to retrieve non-existent singleton 'FireBase' error

I'm running a up to date 3.1dev from master godot branch

```
func _ready():
        if OS.get_name() == "Android":
                firebase = Engine.get_singleton("FireBase")
                firebase.initWithFile("res://godot-firebase-config.json", get_instance_id())
```

**adb logcat :**
`

- 10-09 02:39:42.750 14431 14431 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<
- 10-09 02:39:42.753 14431 14431 I AndroidRuntime: readDownloadBoosterConfig: 'false'
- 10-09 02:39:42.905 14431 14431 D AndroidRuntime: Calling main entry com.android.commands.pm.Pm
- 10-09 02:39:43.520 14431 14431 I AndroidRuntime: VM exiting with result code 0.
- 10-09 02:39:49.520 14483 14483 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<
- 10-09 02:39:49.524 14483 14483 I AndroidRuntime: readDownloadBoosterConfig: 'false'
- 10-09 02:39:49.678 14483 14483 D AndroidRuntime: Calling main entry com.android.commands.pm.Pm
- 10-09 02:39:53.482 14483 14483 I AndroidRuntime: VM exiting with result code 0.
- 10-09 02:39:54.304 14531 14561 I godot   : Loading module: org/godotengine/godot/FireBase
- 10-09 02:39:54.304 14531 14561 I godot   : Loading module: org/godotengine/godot/SQLBridge
- 10-09 02:39:55.914 14531 14586 D FireBase: Refreshed token: [I removed it after paste]
- 10-09 02:39:55.914 14531 14586 D FireBase: Token: [I removed it after paste]
- 10-09 02:40:41.232 14531 14561 I godot   : OpenGL ES 3.0 Renderer: Mali-T830
- 10-09 02:40:43.836 14531 14561 E godot   : **ERROR**: Failed to retrieve non-existent singleton 'FireBase'
- 10-09 02:40:43.836 14531 14561 E godot   :    At: core\engine.cpp:199:get_singleton_object() - Condition ' !E ' is true. returned: __null

`

I don't know if it's an issue from my side or not still, but since the loading of modules seems okay, I have some doubts
Do you have any ideas?

Thank you !

**Comment by RameshRavone** [comment]
Have you done adding [module to project.godot](https://github.com/FrogSquare/GodotFireBase#initialize-firebase)

**Comment by TheTrope** [comment]
Hi !
I added

```
[android]
modules="org/godotengine/godot/FireBase,org/godotengine/godot/SQLBridge"
```
to my project.godot & restarted the editor

But, About this, I didn't do anything: 
`RemoteConfigs default parameters .xml file is at [GODOT-ROOT]/modules/FireBase/res/xml/remote_config_defaults.xml`

Thanks for your help !

**Comment by TheTrope** [comment]
It was an instability from Godot, it has been fixed a few days ago.
I'm closing it
