### ISSUE TITLE
Admob - crashing game and not working Firebase analytics works

### ISSUE THREAD

**Issue by plucian** [FrogSquare/GodotFireBase#38]
hey mate,
I've been trying to implement your nice module into a game and I get a crash when requesting to see if an ad was loaded. Did not get errors when compiling and Firebase analytics works.
Here is my set up:
Godot 2.1.5
godot-firbase-config:
`{
  "AdMob" : true,
  "Authentication" : false,
  "Invites" : true,
  "RemoteConfig" : false,
  "Notification" : false,
  "Storage" : false,
  "Firestore" : false,

  "AuthConf" : 
  {
    "Google" : false,
    "Twitter" : false,
    "Facebook" : false,
    "FacebookAppId" : "1234566789875"
  },

  "Ads" : 
  {
    "AppId": "ca-app-pub-xxxxxxxxxx",
    "BannerAd" : false,
    "BannerGravity" : "BOTTOM",
    "BannerAdId" : "",

    "InterstitialAd" : true,
    "InterstitialAdId" : "ca-app-pub-xxxxxxxxx",

    "RewardedVideoAd" : false,
    "RewardedVideoAdId" : "",

        "TestAds" : true
  }
}`

Config file from Firbase Godot module:
`_config = {
"Analytics"      : True,
"AdMob"          : True,
"Invites"        : True,
"RemoteConfig"   : False,
"Notification"   : False,
"Storage"        : False,
"Firestore"      : False,

"Authentication" : False,
"AuthGoogle"     : True,
"AuthFacebook"   : False,
"AuthTwitter"    : False
}
`

And the code from the game:
`	if OS.get_name() == "Android":
		firebase = Globals.get_singleton("FireBase")
		if firebase:
			firebase.initWithFile("res://godot-firebase-config.json", get_instance_ID());`

and this, crashes the game
`	if firebase:
		if firebase.is_interstitial_loaded():
			firebase.show_interstitial_ad()`

Any ideas ? suggestions ? where should I look for troubles ?
thanks !

**Comment by plucian** [comment]
This is the logcat:
E/AndroidRuntime( 9999): FATAL EXCEPTION: GLThread 844
E/AndroidRuntime( 9999): Process: com.send.tospace, PID: 9999
E/AndroidRuntime( 9999): java.lang.NullPointerException
E/AndroidRuntime( 9999):        at org.godotengine.godot.AdMob.isInterstitialLoaded(AdMob.java:323)
E/AndroidRuntime( 9999):        at org.godotengine.godot.FireBase.is_interstitial_loaded(FireBase.java:275)
E/AndroidRuntime( 9999):        at org.godotengine.godot.GodotLib.step(Native Method)
E/AndroidRuntime( 9999):        at org.godotengine.godot.GodotLib.step(Native Method)
E/AndroidRuntime( 9999):        at org.godotengine.godot.GodotView$Renderer.onDrawFrame(GodotView.java:640)
E/AndroidRuntime( 9999):        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1532)
E/AndroidRuntime( 9999):        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1249)
D/FireBase( 9999): Initializing Firebase Invites.
D/FireBase( 9999): FireBase initialized.
D/FireBase( 9999): AdMob:Interstitial:OnAdLoaded

**Comment by RameshRavone** [comment]
This is happening because `GodotFirebase` is not fully initialized, wait for the callback in `_receive_message`, added a debug message in `isInterstitialLoaded`
