### ISSUE TITLE
Compiling with GodotGoogleService module

### ISSUE THREAD

**Issue by felipemattar** [FrogSquare/GodotFireBase#39]
Im trying compiling together GodotFireBase, GodotSQL and GodotGoogleService modules, anyone have success doing that?

**Comment by umaci** [comment]
Yep, i have compiled sucessfully.

**Comment by homarox** [comment]
Can you give me a link of:
GodotFireBase
GodotSQL
GodotGoogleService
=> I tried some modules, it compiles ok, but can not use because out of date.

**Comment by RameshRavone** [comment]
GodotSql: https://github.com/FrogSquare/GodotSQL
GodotFireBase: https://github.com/FrogSquare/GodotFireBase
GodotGoogleService: https://github.com/FrogSquare/GodotGoogleService

everything is under https://github.com/FrogSquare/ and I did updated the SDK's

And here is a hint if you are building with godot 2.X, just copy `build.gradle.template` and `AndroidManifest.xml.template` from godot 3.1 (master branch) into `platform/android/`
