### ISSUE TITLE
AdMob Receive message from java API has changed but README not updated

### ISSUE THREAD

**Issue by wombatwingdings** [FrogSquare/GodotFireBase#41]
AdMob Receive message from java
```
func _receive_message(tag, from, key, data):
    if tag == "FireBase" and from == "AdMob":
```

This no longer works as tag has changed from "FireBase" to "FrogSquare". Is this intentional? If so, can the README be updated?

Thanks

**Comment by RameshRavone** [comment]
Many Thanks and Fixedb `78a70175db33b44600ffdd650a5597947cc6d6a3`, PR would have been better.

**Comment by wombatwingdings** [comment]
Thanks. Wasn't sure if this was intentional or not to issue Pull Request.
