### ISSUE TITLE
Error trying to compile modules

### ISSUE THREAD

**Issue by Skynoryu** [FrogSquare/GodotFireBase#44]
I change the app_id in the config.py file, but run the scons, I get this message:

scons platform=android target=debug
scons: Reading SConscript files ...
Package xcursor was not found in the pkg-config search path.
Perhaps you should add the directory containing `xcursor.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xcursor' found
xcursor not found.. x11 disabled.
Building for Android (armv7) (with NEON)
Using NDK unified headers
GodotFireBase: Enabled
GodotFireBase: [Analytics, AdMob, Auth, Invites, Notification, RemoteConfig, Firestore, AuthGoogle]
**KeyError: 'application_id':
  File "/home/buildnplay/Desktop/godot-3.0/SConstruct", line 400:
    config.configure(env)
  File "./modules/FireBase/config.py", line 209:
    if env["application_id"] != None:
  File "/usr/lib/scons/SCons/Environment.py", line 410:
    return self._dict[key]**

can anybody help me?

**Comment by RameshRavone** [comment]
It is already fixed.
