### ISSUE TITLE
game crashed during boot

### ISSUE THREAD

**Issue by ramizbalayil** [FrogSquare/GodotFireBase#5]
The game crashes during starting of the app. i have attached the adb logcat. i had enabled analytics, admob and auth. but only google as true. facebook was false.
[logfile.txt](https://github.com/FrogSquare/GodotFireBase/files/1049456/logfile.txt)

**Comment by RameshRavone** [comment]
It is a NullPointerException on GooglePlayService which is not part of `GodotFireBase`

Where is the file: `PlayGameServices.java`

```
06-02 16:07:52.039 14647 14647 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.common.api.GoogleApiClient.connect()' on a null object reference
06-02 16:07:52.039 14647 14647 E AndroidRuntime: 	at org.godotengine.godot.PlayGameServices$2.run(PlayGameServices.java:96)
```

**Comment by RameshRavone** [comment]
Closing as this is not relented to "GodotFireBase"
