### ISSUE TITLE
Can't connect to FireBase database

### ISSUE THREAD

**Issue by plucian** [FrogSquare/GodotFireBase#50]
Everything seems to be working fine, FireBase is initialized, but it is not communicating with Firebase website.. I waited already for 2 days and kept on trying. 
What android user permission are required for this to work ? I'm using 2.1.5 version and that seems to be having a problem with setting permissions.. That might be the culprit, but I thought I'd ask here as well, maybe someone else ran into this problem already..
thanks !

**Comment by plucian** [comment]
Seems the permissions are fine.. Admob is not initializing, not sure why:
D/FrogSquare(30862): Data From File: {"Firestore":false, "AdMob":true, "Google":false, "Ads":{"BannerAd":true, "BannerGravity":"BOTTOM", "InterstitialAdId":"ca-app-pub-3940256099942544/1033173712", "AppId":"ca-app-pub-xxx", "RewardedVideoAdId":"", "TestAds":false, "BannerAdId":"ca-app-pub-xxxxxxxx", "InterstitialAd":false, "RewardedVideoAd":false}, "AuthConf":{"Twitter":false, "Google":false, "FacebookAppID":"1086088244850817", "Facebook":false}, "Authentication":false, "Invites":false, "Facebook":false}
D/FrogSquare(30862): Initializing Firebase Analytics.
D/FrogSquare(30862): Firebase Analytics initialized..!
D/FrogSquare(30862): Initializing Firebase AdMob.
D/FrogSquare(30862): FireBase initialized.
D/FrogSquare(30862): Setting current screen to: Main Menu
D/FrogSquare(30862): AdMob:NotInitialized.
D/FrogSquare(30862): AdMob:Banner:OnAdLoaded

**Comment by RameshRavone** [comment]
What do you mean admob is not initializing, the banner is loaded,

`FrogSquare(30862): AdMob:Banner:OnAdLoaded`

**Comment by plucian** [comment]
Hey Ramesh, that was straight up from the adb logcat.
Anyway I figured it out..somewhat. I'm using 2.1.5 branch. For that to compile correctly, gradle built template from 3.1 is needed. Than for that to work, the last commit should be reverted back since v4 support comes from that template already. 
So your code actually works as advertised, less the last commit though..
