### ISSUE TITLE
More flexible custom logging for Firebase Analytics

### ISSUE THREAD

**Issue by arypbatista** [FrogSquare/GodotFireBase#8]
I think the current `send_custom(String key, String value)` method is ok, but I would like to be able to have some more complex custom logging method available in a way I can define: multiple (key, value) and also the event name.

I think this is much needed to have more complex and flexible logging. For example, I want to have a event category called `level_event` where I group all events regarding level starting/ending/retrials, results and spent time.

```
[level_event] { level_name: 'zone01/level01',  duration: 122100, score: 340 }
[level_event] { level_name: 'zone01/level02',  duration: 62300, score: 50 }
```

I suggest adding a new method, `send_custom(String event, Map<String, String> content)` that will create the log bundle out of the content map and send it as the `event` event.

This method will be accessible from Godot scripts through method `send_event(event, dict)`.

If you agree on this, I can also implement it.

**Comment by RameshRavone** [comment]
This is good, I already have an implementation of this (local repo), will push with some other enhancements...!

**Comment by arypbatista** [comment]
@RameshRavone can you push separately? Or push in a different branch, no matter if it is incomplete, maybe I can take it and isolate the feature in a new branch for pull request.

Or I can write it from scratch, whatever you think it will be better and faster!

**Comment by RameshRavone** [comment]
Been busy with twitter  auth and GodotGoogleService and GodotFacebook, Guess I can push this one earlier, will do.

**Comment by arypbatista** [comment]
Thanks @RameshRavone. Hey, how do you map a GDScript dict value into Java? I am having issues trying to find that.

**Comment by RameshRavone** [comment]
We should use Godot's Dictionary not Map.

**Comment by arypbatista** [comment]
Yeah right. I just read `godot_android.cpp` file and saw the magic. I don't see the Dictionary conversion anywhere, only basic types and arrays. I have tried to use `Dictionary` on Java method signature, but it will create an empty Dictionary. I will relay on json strings for now. Let me know if you find out some way to bridge dictionary values.

**Comment by RameshRavone** [comment]
I think the conversion happens at [java_glue.cpp](
https://github.com/godotengine/godot/blob/master/platform/android/java_glue.cpp)
`_variant_to_jvalue`, but so I'm only using `String` and `JSONObject`

**Comment by arypbatista** [comment]
I couldn't make it work with the Dictionary (would be ideal to use it). My current attempt is (couldn't test it yet):

**FireBase.java**
```Java
public void send_event(final String eventName, String json) {
	if (eventName.length() <= 0 || json.length() <= 0) {
		Utils.d("eventName or json is null.");
		return;
	}

	try {
		final JSONObject jsonObj = new JSONObject(json);
	
		activity.runOnUiThread(new Runnable() {
			public void run() {
				Analytics.getInstance(activity).sendEvent(eventName, jsonObj);
			}
		});

	} catch (JSONException e) {
		Utils.d("Invalid json value.");
	}

}
```

**Analytics.java**
```Java
public void sendEvent(String eventName, JSONObject keyValues) {

	// Generate bundle out of keyValues
	Bundle bundle = new Bundle();
	Iterator<String> keys = keyValues.keys();
	while( keys.hasNext() ) {
		String key = (String)keys.next();
		String value = "";
		try {
			value = (String)keyValues.get(key);
		} catch (JSONException e) {
			Utils.d("Invalid key value for " + key);
		}
		bundle.putString(key, value);
	}

	// Dispatch event
	mFirebaseAnalytics = FirebaseAnalytics.getInstance(activity);
	mFirebaseAnalytics.logEvent(eventName, bundle);
	Utils.d("Sending:App:Event:" + eventName + ":" + bundle.toString());
}
```

Also, are you using some IDE for Android module development? JetBrains/Eclipse?

**Comment by RameshRavone** [comment]
I'm going with `Dictionaries`, [db39de9](https://github.com/FrogSquare/GodotFireBase/commit/db39de993d41b9328c7fee64b763b3a22e324ce4)
